# Generated by Django 4.0.3 on 2025-06-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C02',
            new_name='CO2',
        ),
    ]
